package com.youyu.backend.common.auth;

public enum AdminPermission {
    ADMIN_DASHBOARD_VIEW,
    ADMIN_SUPPORT_CONTEXT_VIEW,
    ADMIN_USERS_VIEW,
    ADMIN_USERS_MANAGE,
    ADMIN_VERIFICATIONS_REVIEW,
    ADMIN_PRODUCTS_VIEW,
    ADMIN_PRODUCTS_REVIEW,
    ADMIN_SHOPS_VIEW,
    ADMIN_SHOPS_MANAGE,
    ADMIN_REPORTS_HANDLE,
    ADMIN_SEARCH_GOVERN,
    ADMIN_SEARCH_LOGS_VIEW,
    ADMIN_ORDERS_READ,
    ADMIN_ORDERS_MANAGE,
    ADMIN_MEDIATION_HANDLE,
    ADMIN_MEDIATION_DECIDE,
    ADMIN_AUDIT_VIEW
}
